### ISSUE TITLE
Charts should indicate what API/version they require

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#273]
e.g. v1, v1beta1.

For the first pass, we could use flags like this to alert the user that they must have particular things enabled on their cluster. Combined with @rimusz's suggested `helm show` command, the user would be able to quickly check what particular things a Chart needed to create.

Example Chart.yaml might be something like this. Assume we have a chart that does the `pi` job, as described in the k8s documentation. It uses a `kind: Job`, which is `v1beta`. And say our chart also uses storage, which i s`v1`

```yaml
name: pi
apiVersions:
    - v1
    - v1beta1
version: 0.1.0 
description: ...
# ... rest of chart is normal
```

We could treat certain apiVersions as stable (e.g. v1), and others as unstable (v1beta1), and so issue a warning for the above:

```
$ helm fetch pi
---> Warning: this chart requires a Kubernetes server with v1beta1 api support.
```

In the future, we might be able to probe the k8s cluster to determine some useful information pre-install.
